CREATE TABLE USERS
(
    ID       INT         NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    ENABLED  INT         NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHORITIES
(
    ID        INT         NOT NULL,
    USERNAME  VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_AUTHORITY_KEY UNIQUE (AUTHORITY)
);

CREATE TABLE USER_AUTHORITY
(
    USER_ID      INT NOT NULL,
    AUTHORITY_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, AUTHORITY_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID),
    CONSTRAINT FK_AUTHORITY_ID FOREIGN KEY (AUTHORITY_ID)
        REFERENCES AUTHORITIES (ID)
);

INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED)
VALUES (1, 'ssiqbal', 'Hello@123', 1);

INSERT INTO AUTHORITIES (ID, USERNAME, AUTHORITY)
VALUES (1, 'ssiqbal', 'Admin');

INSERT INTO AUTHORITIES (ID, USERNAME, AUTHORITY)
VALUES (2, 'aiqbal', 'Manager');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID)
VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID)
VALUES (1, 2);