server:
  port: 6767
  servlet:
    contextPath: /spring-security

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e482d40474aaaec77980
            client-secret: dcd7d4f3b2fabeaf8a8646b0d1d653a4378170e9
